[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[forms]]
  name = "contact"
  
  [forms.settings]
    submission_handling = "forms"
    
  [[forms.notifications]]
    type = "email" 
    event = "submission"
    to = "paul@denhartogh.solutions" 